In [ ]:
import pandas as pd 
import numpy  as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

In [ ]:
df=pd.read_csv('ratings.csv',index_col=0) 

In [ ]:
df.head()


movieId  rating  timestamp
userId                            
1             1     4.0  964982703
1             3     4.0  964981247
1             6     4.0  964982224
1            47     5.0  964983815
1            50     5.0  964982931

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100836 entries, 1 to 610
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   movieId    100836 non-null  int64  
 1   rating     100836 non-null  float64
 2   timestamp  100836 non-null  int64  
dtypes: float64(1), int64(2)
memory usage: 3.1 MB


In [ ]:
df.describe()

movieId         rating     timestamp
count  100836.000000  100836.000000  1.008360e+05
mean    19435.295718       3.501557  1.205946e+09
std     35530.987199       1.042529  2.162610e+08
min         1.000000       0.500000  8.281246e+08
25%      1199.000000       3.000000  1.019124e+09
50%      2991.000000       3.500000  1.186087e+09
75%      8122.000000       4.000000  1.435994e+09
max    193609.000000       5.000000  1.537799e+09

K means cluster creation

In [ ]:
 from  sklearn.cluster import KMeans

In [ ]:
kmeans=KMeans(n_clusters=2)

In [ ]:
kmeans.fit(df.drop('rating',axis=1))

KMeans(n_clusters=2)

In [ ]:
kmeans.cluster_centers_

array([[3.78842417e+04, 1.41690820e+09],
       [4.74003709e+03, 1.03790707e+09]])

In [ ]:
#" clustercenter"is the arithmetic mean of all the points belonging to the cluster
kmeans.cluster_centers_

array([[3.78842417e+04, 1.41690820e+09],
       [4.74003709e+03, 1.03790707e+09]])

Evaluation

In [ ]:
# create a new column for df called 'Cluster' which is 1 for private and 0 for publi 
def converter(cluster):
  if cluster=='Yes':
    return 1 
  else:
      return 0 



In [ ]:
df['Cluster']=df['rating'].apply(converter)

In [ ]:
df.head()

Private  Apps  Accept  Enroll  Top10perc  \
Abilene Christian University     Yes  1660    1232     721         23   
Adelphi University               Yes  2186    1924     512         16   
Adrian College                   Yes  1428    1097     336         22   
Agnes Scott College              Yes   417     349     137         60   
Alaska Pacific University        Yes   193     146      55         16   

                              Top25perc  F.Undergrad  P.Undergrad  Outstate  \
Abilene Christian University         52         2885          537      7440   
Adelphi University                   29         2683         1227     12280   
Adrian College                       50         1036           99     11250   
Agnes Scott College                  89          510           63     12960   
Alaska Pacific University            44          249          869      7560   

                              Room.Board  Books  Personal  PhD  Terminal  \
Abilene Christian University        3300    450      2200   70        78   
Adelphi University                  6450    750      1500   29        30   
Adrian College                      3750    400      1165   53        66   
Agnes Scott College                 5450    450       875   92        97   
Alaska Pacific University           4120    800      1500   76        72   

                              S.F.Ratio  perc.alumni  Expend  Grad.Rate  \
Abilene Christian University       18.1           12    7041         60   
Adelphi University                 12.2           16   10527         56   
Adrian College                     12.9           30    8735         54   
Agnes Scott College                 7.7           37   19016         59   
Alaska Pacific University          11.9            2   10922         15   

                              Cluster  
Abilene Christian University        1  
Adelphi University                  1  
Adrian College                      1  
Agnes Scott College                 1  
Alaska Pacific University           1

In [ ]:
 from  sklearn.metrics  import confusion_matrix,classification_report
print(confusion_matrix(df['Cluster'],kmeans.labels_)) 
print(classification_report(df['Cluster'],kmeans.labels_))

[[44696 56140]
 [    0     0]]
              precision    recall  f1-score   support

           0       1.00      0.44      0.61    100836
           1       0.00      0.00      0.00         0

    accuracy                           0.44    100836
   macro avg       0.50      0.22      0.31    100836
weighted avg       1.00      0.44      0.61    100836



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
